imerg:
    ## account for the `disc.gsfc.nasa.gov`
    username: thean
    password: Treebangbang*007
gsmap:
    ## account for the `hokusai.eorc.jaxa.jp`
    username: thean
    password: TREbang-007