#### Log number
# CRITICAL = 50
# ERROR = 40
# WARNING = 30
# INFO = 20
# DEBUG = 10
# NOTSET = 0

imerg:
  # date format is dd-mm-yyyy
  start_date: 01-01-2023
  stop_date: 02-01-2023
  # imerg_url: https://gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGHHE.06 # Early link
  imerg_url: https://gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGHHL.06 # Late link
  destination: /root/projects/data/IMERG
  retry_max: 3
  retry_wait: 10 # second(s)
  timeout: 100 # second(s)
  ignore_cache: False # When True the script will always check file list from servers and rewrite the cache in /temp
  log_level: 10
  log_wget_level: 10